# Generated by Django 2.2.2 on 2019-07-09 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('details', models.TextField()),
                ('duration', models.IntegerField()),
                ('fee', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
    ]
