# Generated by Django 2.2.2 on 2019-07-09 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DemoApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='fee',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
